-- =============================================================================
-- School Notes - complete schema
--
-- Paste this whole file into the Supabase SQL Editor and run it:
--   https://supabase.com/dashboard/project/djphnnjnxkmrgfrryonw/sql/new
--
-- Generated by scripts/build-schema.sh from supabase/migrations/.
-- Do not edit directly. If you have the Supabase CLI linked, prefer
-- `npm run db:push`. Safe to run once on an empty project.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 20260819000001_core.sql
-- ---------------------------------------------------------------------------

-- Core academic structures: terms, courses, and the reference info that
-- makes a course page useful (instructors, office hours, meetings, links).

create extension if not exists "pgcrypto";

-- Keeps updated_at honest without app-layer discipline.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  -- All reminder/calendar math is done in this zone, not UTC, so "due at
  -- midnight" means midnight where the user actually is.
  timezone text not null default 'America/New_York',
  -- Minutes before due_at to fire reminders, e.g. {10080, 1440, 120}.
  default_reminder_offsets int[] not null default '{1440, 120}',
  quiet_hours_start time,
  quiet_hours_end time,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.terms (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  starts_on date,
  ends_on date,
  is_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index terms_user_idx on public.terms(user_id);

create table public.courses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  term_id uuid references public.terms(id) on delete set null,
  code text,                      -- "CS 3410"
  title text not null,            -- "Computer System Organization"
  section text,
  color text not null default '#6366f1',
  credits numeric(3,1),
  location text,
  notes text,
  canvas_course_id bigint,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index courses_user_idx on public.courses(user_id);
-- One local course per Canvas course, so re-syncing updates instead of duplicating.
create unique index courses_canvas_unique on public.courses(user_id, canvas_course_id)
  where canvas_course_id is not null;

create table public.instructors (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  name text not null,
  role text not null default 'professor',  -- professor | ta | grader | advisor
  email text,
  phone text,
  office text,
  pronouns text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index instructors_course_idx on public.instructors(course_id);

create table public.office_hours (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  instructor_id uuid not null references public.instructors(id) on delete cascade,
  weekday int not null check (weekday between 0 and 6),  -- 0 = Sunday
  starts_at time not null,
  ends_at time not null,
  location text,
  url text,
  by_appointment boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index office_hours_instructor_idx on public.office_hours(instructor_id);

-- Recurring class meetings, used to render a weekly timetable.
create table public.course_meetings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  kind text not null default 'lecture',   -- lecture | lab | discussion | review
  weekday int not null check (weekday between 0 and 6),
  starts_at time not null,
  ends_at time not null,
  location text,
  url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index course_meetings_course_idx on public.course_meetings(course_id);

-- Zoom/Meet/LMS/textbook links. Kept as rows rather than columns so a course
-- can have any number of them without schema churn.
create table public.course_links (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  kind text not null default 'other',  -- zoom | meet | lms | syllabus | textbook | drive | other
  label text not null,
  url text not null,
  passcode text,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index course_links_course_idx on public.course_links(course_id);

create trigger touch_profiles before update on public.profiles
  for each row execute function public.touch_updated_at();
create trigger touch_terms before update on public.terms
  for each row execute function public.touch_updated_at();
create trigger touch_courses before update on public.courses
  for each row execute function public.touch_updated_at();
create trigger touch_instructors before update on public.instructors
  for each row execute function public.touch_updated_at();
create trigger touch_office_hours before update on public.office_hours
  for each row execute function public.touch_updated_at();
create trigger touch_course_meetings before update on public.course_meetings
  for each row execute function public.touch_updated_at();
create trigger touch_course_links before update on public.course_links
  for each row execute function public.touch_updated_at();

-- Give every new auth user a profile row so the app never has to handle a
-- missing-profile case.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email))
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- 20260819000002_content.sql
-- ---------------------------------------------------------------------------

-- Assignments/tests, notes (typed + handwritten), and file attachments.

create type public.work_kind as enum (
  'assignment', 'quiz', 'exam', 'project', 'reading', 'lab', 'discussion', 'other'
);

create type public.work_status as enum (
  'todo', 'in_progress', 'submitted', 'graded', 'dropped'
);

create type public.work_source as enum ('manual', 'canvas', 'gradescope', 'ics');

create table public.assignments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid references public.courses(id) on delete cascade,
  title text not null,
  description text,
  kind public.work_kind not null default 'assignment',
  status public.work_status not null default 'todo',
  due_at timestamptz,
  -- Canvas exposes "all day"/date-only deadlines; the UI must not imply a
  -- precise time when there isn't one.
  due_is_all_day boolean not null default false,
  available_at timestamptz,
  lock_at timestamptz,
  points numeric(8,2),
  score numeric(8,2),
  priority int not null default 2 check (priority between 1 and 4),  -- 1 = highest
  estimated_minutes int,
  url text,
  source public.work_source not null default 'manual',
  canvas_assignment_id bigint,
  -- Snapshot of the last synced upstream payload, used to detect real changes
  -- and to avoid clobbering fields the user edited locally.
  source_hash text,
  completed_at timestamptz,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index assignments_user_due_idx on public.assignments(user_id, due_at);
create index assignments_course_idx on public.assignments(course_id);
create index assignments_status_idx on public.assignments(user_id, status) where archived_at is null;
create unique index assignments_canvas_unique on public.assignments(user_id, canvas_assignment_id)
  where canvas_assignment_id is not null;

create type public.note_kind as enum ('page', 'handwritten', 'mixed');

create table public.notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid references public.courses(id) on delete set null,
  -- Self-reference gives Obsidian-style nesting (unit -> lecture -> subtopic).
  parent_id uuid references public.notes(id) on delete cascade,
  title text not null default 'Untitled',
  kind public.note_kind not null default 'page',
  -- Markdown source of truth for typed content. Handwritten pages keep this
  -- for OCR/transcribed text so search covers ink too.
  body text not null default '',
  -- Free-form tags; indexed with gin for cheap tag filters.
  tags text[] not null default '{}',
  -- Set when this note is the notes-for-a-specific-class-session.
  session_date date,
  is_pinned boolean not null default false,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index notes_user_idx on public.notes(user_id);
create index notes_course_idx on public.notes(course_id);
create index notes_parent_idx on public.notes(parent_id);
create index notes_tags_idx on public.notes using gin(tags);
-- Full-text search across title and body (including ink transcriptions).
create index notes_search_idx on public.notes
  using gin(to_tsvector('english', coalesce(title,'') || ' ' || coalesce(body,'')));

-- Wiki-style [[links]] between notes, resolved on save. Enables backlinks and
-- a graph view without parsing every note body at read time.
create table public.note_links (
  source_note_id uuid not null references public.notes(id) on delete cascade,
  target_note_id uuid not null references public.notes(id) on delete cascade,
  primary key (source_note_id, target_note_id)
);
create index note_links_target_idx on public.note_links(target_note_id);

create type public.attachment_kind as enum ('image', 'pdf', 'ink', 'audio', 'file');

create table public.attachments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  note_id uuid references public.notes(id) on delete cascade,
  course_id uuid references public.courses(id) on delete cascade,
  kind public.attachment_kind not null,
  -- Path within the private 'notes' storage bucket.
  storage_path text not null,
  filename text,
  mime_type text,
  byte_size bigint,
  width int,
  height int,
  -- PencilKit PKDrawing data lives in storage; this holds the stroke count and
  -- canvas size so the web app can render a placeholder without downloading it.
  ink_metadata jsonb,
  page_index int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index attachments_note_idx on public.attachments(note_id);
create index attachments_course_idx on public.attachments(course_id);

-- Syllabi, slide decks, readings: course-level documents that aren't notes.
create table public.documents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id uuid not null references public.courses(id) on delete cascade,
  title text not null,
  kind text not null default 'other',  -- syllabus | slides | reading | rubric | other
  -- Either an uploaded file or an external link.
  storage_path text,
  url text,
  mime_type text,
  byte_size bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint documents_needs_target check (storage_path is not null or url is not null)
);
create index documents_course_idx on public.documents(course_id);

create trigger touch_assignments before update on public.assignments
  for each row execute function public.touch_updated_at();
create trigger touch_notes before update on public.notes
  for each row execute function public.touch_updated_at();
create trigger touch_attachments before update on public.attachments
  for each row execute function public.touch_updated_at();
create trigger touch_documents before update on public.documents
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 20260819000003_integrations.sql
-- ---------------------------------------------------------------------------

-- External integrations (Canvas, Google Calendar, Notion), the calendar-sync
-- ledger, and the reminder queue.

create type public.integration_provider as enum ('canvas', 'google', 'notion', 'gradescope', 'ics');
create type public.integration_status as enum ('connected', 'expired', 'error', 'disconnected');

-- Non-secret connection metadata. Safe for the client to read so the UI can
-- show "Canvas: connected, last synced 4 minutes ago".
create table public.integrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider public.integration_provider not null,
  status public.integration_status not null default 'connected',
  -- Which account this is, for display: "canvas.instructure.com" / an email.
  account_label text,
  -- Provider-specific non-secret config, e.g. {"base_url": "...", "calendar_id": "..."}.
  config jsonb not null default '{}',
  last_synced_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider)
);
create index integrations_user_idx on public.integrations(user_id);

-- Tokens live in a separate table with NO row-level policies, so the anon and
-- authenticated roles can never read them even with a valid JWT. Only the
-- service role (server-side code and Edge Functions) bypasses RLS to reach it.
create table public.integration_secrets (
  integration_id uuid primary key references public.integrations(id) on delete cascade,
  access_token text,
  refresh_token text,
  expires_at timestamptz,
  scopes text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Maps a local assignment to the event it created in an external calendar, so
-- repeated syncs update one event instead of creating duplicates.
create table public.calendar_event_links (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  provider public.integration_provider not null,
  external_calendar_id text,
  external_event_id text not null,
  -- Hash of the pushed payload; lets sync skip unchanged events cheaply.
  content_hash text,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (assignment_id, provider)
);
create index calendar_links_user_idx on public.calendar_event_links(user_id);

create type public.reminder_channel as enum ('push', 'email');
create type public.reminder_status as enum ('pending', 'sent', 'failed', 'skipped', 'cancelled');

create table public.reminders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  -- Minutes before due_at this reminder represents; kept so regeneration can
  -- tell an auto-generated reminder from one the user added by hand.
  offset_minutes int,
  remind_at timestamptz not null,
  channel public.reminder_channel not null default 'push',
  status public.reminder_status not null default 'pending',
  sent_at timestamptz,
  error text,
  is_manual boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  -- Prevents duplicate reminders for the same assignment/offset/channel.
  unique (assignment_id, offset_minutes, channel)
);
-- The dispatcher's hot path: find everything due to fire.
create index reminders_due_idx on public.reminders(remind_at) where status = 'pending';
create index reminders_user_idx on public.reminders(user_id);

-- Web Push endpoints, one per browser/device.
create table public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  device_label text,
  last_used_at timestamptz,
  created_at timestamptz not null default now()
);
create index push_subs_user_idx on public.push_subscriptions(user_id);

-- Observability for every background sync, so a silent Canvas failure is
-- visible in the UI rather than just missing assignments.
create table public.sync_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider public.integration_provider not null,
  direction text not null default 'pull',  -- pull | push
  status text not null default 'running',  -- running | success | error
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  items_created int not null default 0,
  items_updated int not null default 0,
  items_skipped int not null default 0,
  error text
);
create index sync_runs_user_idx on public.sync_runs(user_id, started_at desc);

create trigger touch_integrations before update on public.integrations
  for each row execute function public.touch_updated_at();
create trigger touch_integration_secrets before update on public.integration_secrets
  for each row execute function public.touch_updated_at();
create trigger touch_calendar_links before update on public.calendar_event_links
  for each row execute function public.touch_updated_at();
create trigger touch_reminders before update on public.reminders
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 20260819000004_reminders_rls.sql
-- ---------------------------------------------------------------------------

-- Reminder generation, row-level security, and private storage buckets.

-- Rebuilds the auto-generated reminders for one assignment from the user's
-- preferred offsets. Manual reminders are never touched.
create or replace function public.sync_assignment_reminders(p_assignment_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  a public.assignments;
  offsets int[];
  o int;
  target timestamptz;
begin
  select * into a from public.assignments where id = p_assignment_id;
  if not found then
    return;
  end if;

  delete from public.reminders
   where assignment_id = a.id
     and is_manual = false
     and status = 'pending';

  -- Nothing to remind about: no deadline, archived, or already handed in.
  if a.due_at is null
     or a.archived_at is not null
     or a.status in ('submitted', 'graded', 'dropped') then
    return;
  end if;

  select default_reminder_offsets into offsets from public.profiles where id = a.user_id;
  if offsets is null then
    offsets := '{1440, 120}';
  end if;

  foreach o in array offsets loop
    target := a.due_at - make_interval(mins => o);
    -- Skip offsets already in the past; a reminder for a deadline 20 minutes
    -- out shouldn't also fire the "one week before" notification.
    if target > now() then
      insert into public.reminders (user_id, assignment_id, offset_minutes, remind_at, channel)
      values (a.user_id, a.id, o, target, 'push')
      on conflict (assignment_id, offset_minutes, channel) do update
        set remind_at = excluded.remind_at,
            status    = 'pending',
            error     = null;
    end if;
  end loop;
end;
$$;

create or replace function public.assignments_reminder_trigger()
returns trigger
language plpgsql
as $$
begin
  perform public.sync_assignment_reminders(new.id);
  return new;
end;
$$;

create trigger assignments_sync_reminders
  after insert or update of due_at, status, archived_at on public.assignments
  for each row execute function public.assignments_reminder_trigger();

-- ---------------------------------------------------------------------------
-- Row-level security. Every table is owner-scoped; nothing is world-readable.
-- ---------------------------------------------------------------------------

alter table public.profiles              enable row level security;
alter table public.terms                 enable row level security;
alter table public.courses               enable row level security;
alter table public.instructors           enable row level security;
alter table public.office_hours          enable row level security;
alter table public.course_meetings       enable row level security;
alter table public.course_links          enable row level security;
alter table public.assignments           enable row level security;
alter table public.notes                 enable row level security;
alter table public.note_links            enable row level security;
alter table public.attachments           enable row level security;
alter table public.documents             enable row level security;
alter table public.integrations          enable row level security;
alter table public.integration_secrets   enable row level security;
alter table public.calendar_event_links  enable row level security;
alter table public.reminders             enable row level security;
alter table public.push_subscriptions    enable row level security;
alter table public.sync_runs             enable row level security;

create policy profiles_owner on public.profiles
  for all to authenticated using (id = auth.uid()) with check (id = auth.uid());

create policy terms_owner on public.terms
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy courses_owner on public.courses
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy instructors_owner on public.instructors
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy office_hours_owner on public.office_hours
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy course_meetings_owner on public.course_meetings
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy course_links_owner on public.course_links
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy assignments_owner on public.assignments
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy notes_owner on public.notes
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy attachments_owner on public.attachments
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy documents_owner on public.documents
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy integrations_owner on public.integrations
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy calendar_links_owner on public.calendar_event_links
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy reminders_owner on public.reminders
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy push_subs_owner on public.push_subscriptions
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy sync_runs_owner on public.sync_runs
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

-- note_links has no user_id; ownership is inherited from the source note.
create policy note_links_owner on public.note_links
  for all to authenticated
  using (exists (
    select 1 from public.notes n
     where n.id = note_links.source_note_id and n.user_id = auth.uid()
  ))
  with check (exists (
    select 1 from public.notes n
     where n.id = note_links.source_note_id and n.user_id = auth.uid()
  ));

-- integration_secrets deliberately has NO policy. RLS is on, so anon and
-- authenticated are denied outright; only the service role can read tokens.

-- ---------------------------------------------------------------------------
-- Storage: private buckets, each user confined to a folder named by their uid.
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('notes', 'notes', false), ('documents', 'documents', false)
on conflict (id) do nothing;

create policy notes_bucket_owner on storage.objects
  for all to authenticated
  using (bucket_id = 'notes' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'notes' and (storage.foldername(name))[1] = auth.uid()::text);

create policy documents_bucket_owner on storage.objects
  for all to authenticated
  using (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text)
  with check (bucket_id = 'documents' and (storage.foldername(name))[1] = auth.uid()::text);

-- ---------------------------------------------------------------------------
-- 20260819000005_calendars.sql
-- ---------------------------------------------------------------------------

-- Multiple accounts per provider, external calendar subscriptions, and the
-- cached events that back the in-app calendar view.

-- ---------------------------------------------------------------------------
-- 1. Allow more than one account per provider (e.g. a personal Google account
--    alongside a university one).
-- ---------------------------------------------------------------------------

alter table public.integrations
  add column if not exists external_account_id text not null default '';

-- Existing rows predate the column; the account label is the best identifier
-- we already have for them.
update public.integrations
   set external_account_id = coalesce(account_label, '')
 where external_account_id = '';

alter table public.integrations drop constraint if exists integrations_user_id_provider_key;

-- One row per (user, provider, account). Two Google accounts now coexist.
create unique index if not exists integrations_account_unique
  on public.integrations(user_id, provider, external_account_id);

-- ---------------------------------------------------------------------------
-- 2. Calendar links must be per-integration, not per-provider, now that a user
--    can have two Google accounts.
-- ---------------------------------------------------------------------------

alter table public.calendar_event_links
  add column if not exists integration_id uuid references public.integrations(id) on delete cascade;

update public.calendar_event_links l
   set integration_id = i.id
  from public.integrations i
 where l.integration_id is null
   and i.user_id = l.user_id
   and i.provider = l.provider;

alter table public.calendar_event_links
  drop constraint if exists calendar_event_links_assignment_id_provider_key;

create unique index if not exists calendar_links_assignment_integration_unique
  on public.calendar_event_links(assignment_id, integration_id);

-- ---------------------------------------------------------------------------
-- 3. External calendars the user subscribes to (class schedule, clubs, etc.).
-- ---------------------------------------------------------------------------

create table if not exists public.external_calendars (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  integration_id uuid not null references public.integrations(id) on delete cascade,
  -- Google's calendar id, e.g. an email address or "...@group.calendar.google.com".
  external_id text not null,
  name text not null,
  description text,
  -- Colour Google reports; the user can override it locally.
  color text,
  color_override text,
  timezone text,
  is_primary boolean not null default false,
  -- Whether this calendar is drawn in the app's calendar view.
  is_visible boolean not null default true,
  -- Whether we pull its events at all. Off by default for noisy calendars.
  sync_enabled boolean not null default true,
  -- True for the "School — Assignments & Tests" calendar this app itself
  -- writes to; it must never be re-imported as external events or every
  -- assignment would appear twice in the calendar view.
  is_app_managed boolean not null default false,
  access_role text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (integration_id, external_id)
);
create index if not exists external_calendars_user_idx on public.external_calendars(user_id);

-- ---------------------------------------------------------------------------
-- 4. Cached events from those calendars.
--
--    Google recurrence rules are expanded server-side (singleEvents=true), so
--    each row here is one concrete occurrence. That keeps the calendar view a
--    simple range query instead of an RRULE evaluator.
-- ---------------------------------------------------------------------------

create table if not exists public.calendar_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  calendar_id uuid not null references public.external_calendars(id) on delete cascade,
  external_event_id text not null,
  title text not null default '(no title)',
  description text,
  location text,
  url text,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  is_all_day boolean not null default false,
  status text,
  -- Present when this row is one instance of a recurring series.
  recurring_event_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (calendar_id, external_event_id)
);
create index if not exists calendar_events_user_range_idx
  on public.calendar_events(user_id, starts_at);
create index if not exists calendar_events_calendar_idx
  on public.calendar_events(calendar_id);

-- ---------------------------------------------------------------------------
-- 5. Class meetings need to be visible on the calendar too. course_meetings
--    already stores the weekly pattern; these columns bound it to the weeks the
--    class actually runs, so a Tuesday lecture doesn't render over the summer.
-- ---------------------------------------------------------------------------

alter table public.course_meetings
  add column if not exists starts_on date,
  add column if not exists ends_on date;

-- ---------------------------------------------------------------------------
-- 6. RLS for the new tables.
-- ---------------------------------------------------------------------------

alter table public.external_calendars enable row level security;
alter table public.calendar_events    enable row level security;

drop policy if exists external_calendars_owner on public.external_calendars;
create policy external_calendars_owner on public.external_calendars
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists calendar_events_owner on public.calendar_events;
create policy calendar_events_owner on public.calendar_events
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop trigger if exists touch_external_calendars on public.external_calendars;
create trigger touch_external_calendars before update on public.external_calendars
  for each row execute function public.touch_updated_at();

drop trigger if exists touch_calendar_events on public.calendar_events;
create trigger touch_calendar_events before update on public.calendar_events
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 20260819000006_note_search.sql
-- ---------------------------------------------------------------------------

-- Full-text search for notes.
--
-- The original index was on an expression, to_tsvector(title || body). That
-- works for raw SQL but PostgREST can only run textSearch against a real
-- column, so searching from the app was impossible. A generated column fixes
-- that and keeps the vector in sync automatically.

alter table public.notes
  add column if not exists search_vector tsvector
  generated always as (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(body, '')), 'B')
  ) stored;

-- Title matches should outrank body matches, hence the setweight above.
drop index if exists public.notes_search_idx;
create index if not exists notes_search_vector_idx
  on public.notes using gin(search_vector);

-- Ordering the notes list by recency is the common read.
create index if not exists notes_updated_idx
  on public.notes(user_id, updated_at desc)
  where archived_at is null;

-- ---------------------------------------------------------------------------
-- 20260819000007_notion.sql
-- ---------------------------------------------------------------------------

-- Notion sync: maps assignments to the pages created for them.
--
-- Deliberately not reusing calendar_event_links: that table is keyed around
-- calendar semantics, and a table named for calendars holding Notion pages is
-- the kind of thing that misleads later.

create table if not exists public.notion_page_links (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  assignment_id uuid not null references public.assignments(id) on delete cascade,
  integration_id uuid not null references public.integrations(id) on delete cascade,
  -- The Notion database the page lives in, and the page itself.
  database_id text not null,
  page_id text not null,
  -- Hash of the pushed properties; unchanged pages are skipped.
  content_hash text,
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (assignment_id, integration_id)
);
create index if not exists notion_links_user_idx on public.notion_page_links(user_id);

alter table public.notion_page_links enable row level security;

drop policy if exists notion_links_owner on public.notion_page_links;
create policy notion_links_owner on public.notion_page_links
  for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

drop trigger if exists touch_notion_links on public.notion_page_links;
create trigger touch_notion_links before update on public.notion_page_links
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------------
-- 20260819000008_dedupe_pref.sql
-- ---------------------------------------------------------------------------

-- Whether to hide external calendar events that duplicate a class already on
-- the timetable.
--
-- On by default: a university publishing class times to Google is common, and
-- seeing every lecture twice makes the calendar useless. Off is available for
-- anyone whose events don't actually duplicate.

alter table public.profiles
  add column if not exists hide_duplicate_class_events boolean not null default true;
