#!/usr/bin/env bash
# Regenerates supabase/schema.sql - a single paste-ready file containing every
# migration in order, for first-time setup via the Supabase SQL Editor.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/supabase/schema.sql"
REF="${SUPABASE_PROJECT_REF:-YOUR_PROJECT_REF}"

{
  cat <<HEADER
-- =============================================================================
-- School Notes - complete schema
--
-- Paste this whole file into the Supabase SQL Editor and run it:
--   https://supabase.com/dashboard/project/$REF/sql/new
--
-- Generated by scripts/build-schema.sh from supabase/migrations/.
-- Do not edit directly. If you have the Supabase CLI linked, prefer
-- \`npm run db:push\`. Safe to run once on an empty project.
-- =============================================================================
HEADER

  for f in "$ROOT"/supabase/migrations/*.sql; do
    printf '\n-- %s\n-- %s\n-- %s\n\n' \
      "---------------------------------------------------------------------------" \
      "$(basename "$f")" \
      "---------------------------------------------------------------------------"
    cat "$f"
  done
} > "$OUT"

echo "✓ wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
